// Complete dataset of 100+ companies with detailed information for placement preparation

export interface Company {
  id: string
  name: string
  logo: string
  industry: string
  size: string
  headquarters: string
  description: string
  website?: string
  founded?: number
  activeRoles: string[]
  hiringTrend: "increasing" | "stable" | "decreasing"
  seasonalPattern: string
  minCGPA: number
  degreeRequirements: string[]
  branchesAccepted: string[]
  salaryRanges: {
    level: string
    min: number
    max: number
    location: string
  }[]
  interviewProcess: {
    roundNumber: number
    name: string
    description: string
    difficulty: "easy" | "medium" | "hard"
    topics: string[]
  }[]
  lastHiringCycle: string
  placementRate: number
  averagePackage: number
}

export const companies: Company[] = [
  {
    id: "google",
    name: "Google",
    logo: "🔍",
    industry: "Technology",
    size: "Large",
    headquarters: "Mountain View, CA",
    description: "Global tech giant focused on search, cloud computing, and AI solutions",
    website: "google.com",
    founded: 1998,
    activeRoles: ["Software Engineer", "Data Scientist", "Product Manager", "UX Designer"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak hiring: Sep-Nov, Feb-Apr",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech", "B.Sc", "M.Sc"],
    branchesAccepted: ["CSE", "IT", "ECE", "EE"],
    salaryRanges: [
      { level: "Junior Engineer (L3)", min: 20, max: 25, location: "Bangalore" },
      { level: "Senior Engineer (L4)", min: 30, max: 40, location: "Bangalore" },
      { level: "Staff Engineer (L5)", min: 50, max: 70, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Coding",
        description: "2 coding problems on LeetCode level",
        difficulty: "hard",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Design scalable systems",
        difficulty: "hard",
        topics: ["System Design", "Distributed Systems"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Leadership and teamwork assessment",
        difficulty: "medium",
        topics: ["Behavioral", "Leadership"],
      },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 92,
    averagePackage: 32,
  },
  {
    id: "amazon",
    name: "Amazon",
    logo: "📦",
    industry: "E-commerce & Cloud",
    size: "Large",
    headquarters: "Seattle, WA",
    description: "World's largest e-commerce and cloud computing platform",
    website: "amazon.com",
    founded: 1994,
    activeRoles: ["SDE", "Solutions Architect", "Data Engineer", "Operations Manager"],
    hiringTrend: "stable",
    seasonalPattern: "Peak hiring: Aug-Oct, Jan-Mar",
    minCGPA: 6.8,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "SDE 1", min: 18, max: 24, location: "Bangalore" },
      { level: "SDE 2", min: 28, max: 38, location: "Bangalore" },
      { level: "SDE 3", min: 45, max: 60, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding round with 2 problems",
        difficulty: "medium",
        topics: ["Arrays", "Strings", "Trees"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "DSA focused",
        difficulty: "hard",
        topics: ["DSA", "Optimization"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Problem solving and optimization",
        difficulty: "hard",
        topics: ["System Design", "Problem Solving"],
      },
      {
        roundNumber: 4,
        name: "Bar Raiser",
        description: "Behavioral and competency-based",
        difficulty: "medium",
        topics: ["Behavioral", "Leadership"],
      },
    ],
    lastHiringCycle: "Aug 2024",
    placementRate: 88,
    averagePackage: 30,
  },
  {
    id: "microsoft",
    name: "Microsoft",
    logo: "🪟",
    industry: "Technology",
    size: "Large",
    headquarters: "Redmond, WA",
    description: "Software and cloud computing leader",
    website: "microsoft.com",
    founded: 1975,
    activeRoles: ["SDE", "Cloud Solution Architect", "Data Scientist", "Intern"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round hiring, peak Sep-Nov",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech", "B.Sc"],
    branchesAccepted: ["CSE", "IT", "ECE"],
    salaryRanges: [
      { level: "SDE 1", min: 21, max: 26, location: "Bangalore" },
      { level: "SDE 2", min: 32, max: 42, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screening",
        description: "Initial coding assessment",
        difficulty: "medium",
        topics: ["DSA"],
      },
      {
        roundNumber: 2,
        name: "Technical Interviews",
        description: "2 rounds of problem solving",
        difficulty: "hard",
        topics: ["Algorithms", "Data Structures"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Team fit and experience",
        difficulty: "easy",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 90,
    averagePackage: 31,
  },
  {
    id: "meta",
    name: "Meta",
    logo: "📘",
    industry: "Social Media & Technology",
    size: "Large",
    headquarters: "Menlo Park, CA",
    description: "Social media and metaverse technology company",
    website: "meta.com",
    founded: 2004,
    activeRoles: ["Software Engineer", "Data Scientist", "Product Manager", "ML Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Sep-Nov, Feb-Apr",
    minCGPA: 7.5,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "E3", min: 24, max: 30, location: "Bangalore" },
      { level: "E4", min: 36, max: 48, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Coding Round",
        description: "2-3 algorithmic problems",
        difficulty: "hard",
        topics: ["Advanced DSA", "Optimization"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Design at scale",
        difficulty: "hard",
        topics: ["System Architecture", "Distributed Computing"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Culture and impact",
        difficulty: "medium",
        topics: ["Behavioral", "Leadership"],
      },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 85,
    averagePackage: 35,
  },
  {
    id: "apple",
    name: "Apple",
    logo: "🍎",
    industry: "Consumer Electronics",
    size: "Large",
    headquarters: "Cupertino, CA",
    description: "Premium consumer electronics and software company",
    website: "apple.com",
    founded: 1976,
    activeRoles: ["Software Engineer", "Hardware Engineer", "ML Engineer", "Intern"],
    hiringTrend: "stable",
    seasonalPattern: "Focused hiring: Aug-Oct, Jan-Mar",
    minCGPA: 7.2,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT", "ECE"],
    salaryRanges: [
      { level: "Software Engineer", min: 22, max: 28, location: "Bangalore" },
      { level: "Senior Engineer", min: 38, max: 52, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Screening",
        description: "Initial technical assessment",
        difficulty: "medium",
        topics: ["Coding", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical",
        description: "In-depth problem solving",
        difficulty: "hard",
        topics: ["Advanced DSA", "System Design"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Culture and values",
        difficulty: "easy",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 82,
    averagePackage: 32,
  },
  {
    id: "netflix",
    name: "Netflix",
    logo: "🎬",
    industry: "Entertainment & Technology",
    size: "Large",
    headquarters: "Los Gatos, CA",
    description: "Streaming and entertainment platform",
    website: "netflix.com",
    founded: 1997,
    activeRoles: ["Software Engineer", "Data Engineer", "ML Engineer", "Product Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Sep-Dec",
    minCGPA: 7.3,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 25, max: 32, location: "Bangalore" },
      { level: "Senior Engineer", min: 42, max: 55, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Coding",
        description: "Medium to hard DSA problems",
        difficulty: "hard",
        topics: ["Algorithms", "Data Structures"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Large-scale system design",
        difficulty: "hard",
        topics: ["Distributed Systems", "Architecture"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Team dynamics",
        difficulty: "medium",
        topics: ["Behavioral", "Communication"],
      },
    ],
    lastHiringCycle: "Nov 2024",
    placementRate: 86,
    averagePackage: 34,
  },
  {
    id: "tcs",
    name: "Tata Consultancy Services",
    logo: "🏢",
    industry: "IT Services",
    size: "Large",
    headquarters: "Mumbai, India",
    description: "India's largest IT services company",
    website: "tcs.com",
    founded: 1968,
    activeRoles: ["Software Developer", "Systems Engineer", "Associate", "Trainee"],
    hiringTrend: "stable",
    seasonalPattern: "Continuous hiring, peak Dec-Feb",
    minCGPA: 6.0,
    degreeRequirements: ["B.Tech", "B.Sc", "B.C.A"],
    branchesAccepted: ["CSE", "IT", "ECE", "Mechanical"],
    salaryRanges: [
      { level: "Fresher", min: 3.6, max: 4.2, location: "India" },
      { level: "Associate", min: 5.5, max: 7.0, location: "India" },
      { level: "Senior Associate", min: 8.5, max: 12.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Test",
        description: "Aptitude, reasoning, coding",
        difficulty: "easy",
        topics: ["Aptitude", "Basic Programming"],
      },
      {
        roundNumber: 2,
        name: "Technical Interview",
        description: "Technical fundamentals",
        difficulty: "easy",
        topics: ["Programming", "CS Fundamentals"],
      },
      {
        roundNumber: 3,
        name: "HR Round",
        description: "HR and cultural fit",
        difficulty: "easy",
        topics: ["HR", "Communication"],
      },
    ],
    lastHiringCycle: "Feb 2025",
    placementRate: 95,
    averagePackage: 5.2,
  },
  {
    id: "infosys",
    name: "Infosys",
    logo: "♾️",
    industry: "IT Services",
    size: "Large",
    headquarters: "Bangalore, India",
    description: "Global IT services and consulting company",
    website: "infosys.com",
    founded: 1981,
    activeRoles: ["Power Programmer", "Systems Engineer", "Associate", "Specialist Programmer"],
    hiringTrend: "stable",
    seasonalPattern: "Continuous, peak Oct-Dec",
    minCGPA: 6.0,
    degreeRequirements: ["B.Tech", "B.Sc", "B.C.A", "M.Tech"],
    branchesAccepted: ["CSE", "IT", "ECE", "All Branches"],
    salaryRanges: [
      { level: "Fresher", min: 3.8, max: 4.5, location: "India" },
      { level: "Associate", min: 6.0, max: 8.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Aptitude Test",
        description: "Logical reasoning and quant",
        difficulty: "easy",
        topics: ["Aptitude"],
      },
      {
        roundNumber: 2,
        name: "Technical Round",
        description: "Programming and data structures",
        difficulty: "medium",
        topics: ["Programming", "DSA"],
      },
      {
        roundNumber: 3,
        name: "HR Round",
        description: "HR discussion",
        difficulty: "easy",
        topics: ["HR", "Behavior"],
      },
    ],
    lastHiringCycle: "Jan 2025",
    placementRate: 92,
    averagePackage: 5.5,
  },
  {
    id: "wipro",
    name: "Wipro",
    logo: "🎯",
    industry: "IT Services",
    size: "Large",
    headquarters: "Bangalore, India",
    description: "Global IT services and consulting organization",
    website: "wipro.com",
    founded: 1980,
    activeRoles: ["Project Engineer", "Senior Project Engineer", "Specialist", "Associate"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Nov-Jan",
    minCGPA: 6.5,
    degreeRequirements: ["B.Tech", "B.Sc", "B.C.A"],
    branchesAccepted: ["CSE", "IT", "ECE"],
    salaryRanges: [
      { level: "Fresher", min: 4.0, max: 4.6, location: "India" },
      { level: "Project Engineer", min: 6.0, max: 8.5, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Aptitude and coding",
        difficulty: "easy",
        topics: ["Aptitude", "Programming"],
      },
      {
        roundNumber: 2,
        name: "Technical Interview",
        description: "Technical questions",
        difficulty: "medium",
        topics: ["DSA", "Programming"],
      },
      { roundNumber: 3, name: "HR Round", description: "Final round", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Dec 2024",
    placementRate: 90,
    averagePackage: 5.3,
  },
  {
    id: "hcl",
    name: "HCL Technologies",
    logo: "💻",
    industry: "IT Services",
    size: "Large",
    headquarters: "Noida, India",
    description: "Leading IT services and solutions company",
    website: "hcl.com",
    founded: 1976,
    activeRoles: ["Associate Developer", "Developer", "Systems Engineer", "Analyst"],
    hiringTrend: "stable",
    seasonalPattern: "Continuous hiring",
    minCGPA: 6.0,
    degreeRequirements: ["B.Tech", "B.Sc", "B.C.A"],
    branchesAccepted: ["All Branches"],
    salaryRanges: [
      { level: "Fresher", min: 3.5, max: 4.2, location: "India" },
      { level: "Experienced", min: 5.5, max: 8.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Written Test",
        description: "Aptitude and English",
        difficulty: "easy",
        topics: ["General Aptitude"],
      },
      {
        roundNumber: 2,
        name: "Technical Round",
        description: "Technical fundamentals",
        difficulty: "medium",
        topics: ["Programming", "CS Basics"],
      },
      { roundNumber: 3, name: "HR Round", description: "HR interview", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Jan 2025",
    placementRate: 88,
    averagePackage: 4.5,
  },
  {
    id: "accenture",
    name: "Accenture",
    logo: "▶️",
    industry: "IT Consulting",
    size: "Large",
    headquarters: "Dublin, Ireland",
    description: "Leading professional services company",
    website: "accenture.com",
    founded: 1989,
    activeRoles: ["Associate Software Engineer", "Analyst", "Specialist", "Manager"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Sep-Nov, Mar-May",
    minCGPA: 6.0,
    degreeRequirements: ["B.Tech", "B.Sc", "M.Tech"],
    branchesAccepted: ["CSE", "IT", "All Branches"],
    salaryRanges: [
      { level: "ASE", min: 4.0, max: 4.8, location: "India" },
      { level: "SE", min: 6.0, max: 9.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Test",
        description: "Aptitude, logical reasoning",
        difficulty: "easy",
        topics: ["General Aptitude"],
      },
      {
        roundNumber: 2,
        name: "Technical Round",
        description: "Technical skills",
        difficulty: "medium",
        topics: ["Programming", "DSA"],
      },
      { roundNumber: 3, name: "HR Round", description: "HR and culture fit", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 91,
    averagePackage: 5.0,
  },
  {
    id: "cognizant",
    name: "Cognizant",
    logo: "🧠",
    industry: "IT Services",
    size: "Large",
    headquarters: "Teaneck, New Jersey",
    description: "Digital operations and IT consulting",
    website: "cognizant.com",
    founded: 1994,
    activeRoles: ["Programmer Analyst", "Associate", "Developer", "Consultant"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Dec-Feb",
    minCGPA: 6.0,
    degreeRequirements: ["B.Tech", "B.Sc", "B.C.A"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "PA", min: 4.5, max: 5.2, location: "India" },
      { level: "Senior PA", min: 7.0, max: 10.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Round",
        description: "Aptitude and programming",
        difficulty: "easy",
        topics: ["Aptitude", "Basic Programming"],
      },
      {
        roundNumber: 2,
        name: "Technical Interview",
        description: "Technical assessment",
        difficulty: "medium",
        topics: ["Programming", "Problem Solving"],
      },
      { roundNumber: 3, name: "HR Round", description: "Final HR round", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Jan 2025",
    placementRate: 89,
    averagePackage: 5.2,
  },
  {
    id: "capgemini",
    name: "Capgemini",
    logo: "🔷",
    industry: "IT Consulting",
    size: "Large",
    headquarters: "Paris, France",
    description: "Consulting, technology and outsourcing services",
    website: "capgemini.com",
    founded: 1967,
    activeRoles: ["Consultant", "Senior Consultant", "Manager", "Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Continuous, peak Nov-Jan",
    minCGPA: 6.0,
    degreeRequirements: ["B.Tech", "B.Sc", "M.Tech"],
    branchesAccepted: ["CSE", "IT", "All Branches"],
    salaryRanges: [
      { level: "Fresher", min: 4.2, max: 5.0, location: "India" },
      { level: "Consultant", min: 7.0, max: 11.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Aptitude test",
        difficulty: "easy",
        topics: ["General Aptitude"],
      },
      {
        roundNumber: 2,
        name: "Technical Round",
        description: "Technical interview",
        difficulty: "medium",
        topics: ["Programming"],
      },
      { roundNumber: 3, name: "HR Round", description: "HR discussion", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Dec 2024",
    placementRate: 90,
    averagePackage: 5.0,
  },
  {
    id: "deloitte",
    name: "Deloitte",
    logo: "🎖️",
    industry: "Consulting & Professional Services",
    size: "Large",
    headquarters: "London, United Kingdom",
    description: "Professional services and management consulting",
    website: "deloitte.com",
    founded: 1845,
    activeRoles: ["Analyst", "Consultant", "Senior Associate", "Manager"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Aug-Oct, Feb-Apr",
    minCGPA: 6.5,
    degreeRequirements: ["B.Tech", "B.Sc", "M.B.A", "M.Tech"],
    branchesAccepted: ["All Branches"],
    salaryRanges: [
      { level: "Analyst", min: 5.0, max: 6.0, location: "India" },
      { level: "Consultant", min: 8.5, max: 13.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Test",
        description: "Case studies and reasoning",
        difficulty: "medium",
        topics: ["Analytical Skills", "Case Study"],
      },
      {
        roundNumber: 2,
        name: "Case Discussion",
        description: "Problem-solving case study",
        difficulty: "medium",
        topics: ["Case Analysis"],
      },
      { roundNumber: 3, name: "HR Round", description: "Final interview", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 87,
    averagePackage: 6.0,
  },
  {
    id: "pwc",
    name: "PwC",
    logo: "🔶",
    industry: "Professional Services",
    size: "Large",
    headquarters: "London, United Kingdom",
    description: "Professional services and audit firm",
    website: "pwc.com",
    founded: 1998,
    activeRoles: ["Associate", "Senior Associate", "Manager", "Consultant"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 6.5,
    degreeRequirements: ["B.Tech", "B.Sc", "M.Tech", "M.B.A"],
    branchesAccepted: ["All Branches"],
    salaryRanges: [
      { level: "Associate", min: 5.5, max: 6.5, location: "India" },
      { level: "Senior Associate", min: 9.0, max: 14.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Aptitude and logical reasoning",
        difficulty: "medium",
        topics: ["Reasoning", "Aptitude"],
      },
      {
        roundNumber: 2,
        name: "Case Study",
        description: "Business problem-solving",
        difficulty: "medium",
        topics: ["Problem Solving"],
      },
      { roundNumber: 3, name: "HR Round", description: "Final round", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Nov 2024",
    placementRate: 88,
    averagePackage: 6.5,
  },
  {
    id: "ey",
    name: "EY (Ernst & Young)",
    logo: "🟡",
    industry: "Professional Services",
    size: "Large",
    headquarters: "London, United Kingdom",
    description: "Audit, tax, consulting, and advisory services",
    website: "ey.com",
    founded: 1989,
    activeRoles: ["Associate Consultant", "Consultant", "Senior Consultant", "Manager"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Aug-Oct, Jan-Mar",
    minCGPA: 6.5,
    degreeRequirements: ["B.Tech", "B.Sc", "M.Tech"],
    branchesAccepted: ["CSE", "IT", "All Branches"],
    salaryRanges: [
      { level: "AC", min: 5.2, max: 6.2, location: "India" },
      { level: "Consultant", min: 9.0, max: 13.0, location: "India" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Round",
        description: "Aptitude and case scenarios",
        difficulty: "medium",
        topics: ["Analytical Skills"],
      },
      {
        roundNumber: 2,
        name: "Case Discussion",
        description: "Business consulting case",
        difficulty: "medium",
        topics: ["Business Analysis"],
      },
      { roundNumber: 3, name: "HR Round", description: "HR interview", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 89,
    averagePackage: 6.2,
  },
  {
    id: "goldman",
    name: "Goldman Sachs",
    logo: "💰",
    industry: "Banking & Finance",
    size: "Large",
    headquarters: "New York, USA",
    description: "Leading global investment banking and financial services",
    website: "gs.com",
    founded: 1869,
    activeRoles: ["Analyst", "Associate", "Vice President", "Managing Director"],
    hiringTrend: "stable",
    seasonalPattern: "Peak hiring: Sep-Nov",
    minCGPA: 8.0,
    degreeRequirements: ["B.Tech", "B.Sc", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Analyst", min: 15, max: 18, location: "Bangalore" },
      { level: "Associate", min: 25, max: 35, location: "Bangalore" },
      { level: "VP", min: 50, max: 80, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding and problem solving",
        difficulty: "hard",
        topics: ["DSA", "Algorithms"],
      },
      {
        roundNumber: 2,
        name: "Superday 1",
        description: "Multiple technical rounds",
        difficulty: "hard",
        topics: ["Advanced DSA", "System Design"],
      },
      {
        roundNumber: 3,
        name: "Superday 2",
        description: "Behavioral and technical",
        difficulty: "hard",
        topics: ["Behavioral", "Problem Solving"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 75,
    averagePackage: 28,
  },
  {
    id: "jpmorgan",
    name: "JPMorgan Chase",
    logo: "🏦",
    industry: "Banking & Finance",
    size: "Large",
    headquarters: "New York, USA",
    description: "American multinational investment bank",
    website: "jpmorganchase.com",
    founded: 1871,
    activeRoles: ["Technology Analyst", "Software Engineer", "Quantitative Analyst", "Vice President"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Oct-Nov",
    minCGPA: 7.5,
    degreeRequirements: ["B.Tech", "B.Sc", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Analyst", min: 14, max: 17, location: "Bangalore" },
      { level: "Associate", min: 24, max: 32, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding and aptitude",
        difficulty: "hard",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Interview",
        description: "Advanced problem solving",
        difficulty: "hard",
        topics: ["Advanced DSA", "System Design"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Leadership and teamwork",
        difficulty: "medium",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Nov 2024",
    placementRate: 78,
    averagePackage: 26,
  },
  {
    id: "morgan-stanley",
    name: "Morgan Stanley",
    logo: "📈",
    industry: "Banking & Finance",
    size: "Large",
    headquarters: "New York, USA",
    description: "Financial advisory and capital markets services",
    website: "morganstanley.com",
    founded: 1935,
    activeRoles: ["Technology Analyst", "Analyst", "Associate", "Vice President"],
    hiringTrend: "stable",
    seasonalPattern: "Peak: Sep-Nov",
    minCGPA: 7.5,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Analyst", min: 14, max: 17, location: "Bangalore" },
      { level: "Associate", min: 23, max: 31, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Test",
        description: "Coding problems",
        difficulty: "hard",
        topics: ["DSA", "Algorithms"],
      },
      {
        roundNumber: 2,
        name: "Technical Rounds",
        description: "2 technical interviews",
        difficulty: "hard",
        topics: ["Advanced DSA", "System Design"],
      },
      { roundNumber: 3, name: "Behavioral", description: "HR and fit", difficulty: "medium", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 76,
    averagePackage: 25,
  },
  {
    id: "de-shaw",
    name: "D.E. Shaw",
    logo: "💹",
    industry: "Quant & Finance",
    size: "Medium",
    headquarters: "New York, USA",
    description: "Leading quantitative trading and software development firm",
    website: "deshaw.com",
    founded: 1988,
    activeRoles: ["Software Developer", "Quantitative Analyst", "Associate", "Researcher"],
    hiringTrend: "increasing",
    seasonalPattern: "Continuous hiring",
    minCGPA: 7.8,
    degreeRequirements: ["B.Tech", "M.Tech", "B.Sc"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Developer", min: 22, max: 28, location: "Bangalore" },
      { level: "Senior Developer", min: 40, max: 55, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Coding Round",
        description: "Advanced algorithmic problems",
        difficulty: "hard",
        topics: ["Advanced Algorithms", "Optimization"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Large-scale system design",
        difficulty: "hard",
        topics: ["Distributed Systems", "Architecture"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Culture and values",
        difficulty: "medium",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 70,
    averagePackage: 32,
  },
  {
    id: "citadel",
    name: "Citadel",
    logo: "🏛️",
    industry: "Quantitative Trading",
    size: "Large",
    headquarters: "Chicago, USA",
    description: "Quantitative investment firm",
    website: "citadel.com",
    founded: 1990,
    activeRoles: ["Software Engineer", "Quantitative Researcher", "Analyst", "Associate"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round",
    minCGPA: 7.8,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 24, max: 32, location: "Bangalore" },
      { level: "Senior Engineer", min: 45, max: 65, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding assessment",
        difficulty: "hard",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Rounds",
        description: "Multiple technical interviews",
        difficulty: "hard",
        topics: ["Advanced DSA", "System Design"],
      },
      {
        roundNumber: 3,
        name: "Partner Round",
        description: "Final executive round",
        difficulty: "medium",
        topics: ["Behavioral", "Fit"],
      },
    ],
    lastHiringCycle: "Nov 2024",
    placementRate: 68,
    averagePackage: 36,
  },
  {
    id: "flipkart",
    name: "Flipkart",
    logo: "🛒",
    industry: "E-commerce",
    size: "Large",
    headquarters: "Bangalore, India",
    description: "India's largest e-commerce platform",
    website: "flipkart.com",
    founded: 2007,
    activeRoles: ["SDE 1", "SDE 2", "Android Developer", "Data Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Aug-Oct, Feb-Apr",
    minCGPA: 6.5,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "SDE 1", min: 12, max: 16, location: "Bangalore" },
      { level: "SDE 2", min: 20, max: 28, location: "Bangalore" },
      { level: "SDE 3", min: 35, max: 50, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Coding",
        description: "Medium to hard DSA",
        difficulty: "hard",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "In-depth coding",
        difficulty: "hard",
        topics: ["Algorithms", "Optimization"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "System design and architecture",
        difficulty: "hard",
        topics: ["System Design", "Distributed Computing"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR and fit", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 85,
    averagePackage: 20,
  },
  {
    id: "swiggy",
    name: "Swiggy",
    logo: "🍽️",
    industry: "On-demand Delivery",
    size: "Large",
    headquarters: "Bangalore, India",
    description: "Food delivery and logistics platform",
    website: "swiggy.com",
    founded: 2014,
    activeRoles: ["Backend Engineer", "Android Engineer", "Data Engineer", "Product Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Sep-Nov, Mar-May",
    minCGPA: 6.8,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "SDE 1", min: 13, max: 17, location: "Bangalore" },
      { level: "SDE 2", min: 22, max: 30, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding round",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "In-depth DSA",
        difficulty: "hard",
        topics: ["Algorithms", "Data Structures"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "System design",
        difficulty: "hard",
        topics: ["System Architecture", "Scalability"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR round", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 82,
    averagePackage: 19,
  },
  {
    id: "uber",
    name: "Uber",
    logo: "🚗",
    industry: "Ride-sharing & Logistics",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Ride-sharing and logistics platform",
    website: "uber.com",
    founded: 2009,
    activeRoles: ["Software Engineer", "Data Engineer", "Android Engineer", "ML Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 7.2,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "SE 1", min: 18, max: 24, location: "Bangalore" },
      { level: "SE 2", min: 28, max: 38, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Coding",
        description: "LeetCode medium-hard",
        difficulty: "hard",
        topics: ["DSA", "Optimization"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "Coding and problem solving",
        difficulty: "hard",
        topics: ["Algorithms", "Problem Solving"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "System design",
        difficulty: "hard",
        topics: ["System Architecture", "Distributed Systems"],
      },
      {
        roundNumber: 4,
        name: "Behavioral",
        description: "Leadership and culture",
        difficulty: "medium",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 80,
    averagePackage: 26,
  },
  {
    id: "airbnb",
    name: "Airbnb",
    logo: "🏠",
    industry: "Hospitality & Travel",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Online marketplace for lodging and tourism",
    website: "airbnb.com",
    founded: 2008,
    activeRoles: ["Software Engineer", "Data Scientist", "Product Manager", "ML Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Peak: Aug-Oct, Feb-Apr",
    minCGPA: 7.3,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "SE 1", min: 20, max: 26, location: "Bangalore" },
      { level: "SE 2", min: 32, max: 42, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Coding",
        description: "Medium to hard problems",
        difficulty: "hard",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Large-scale system design",
        difficulty: "hard",
        topics: ["System Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Values and fit",
        difficulty: "medium",
        topics: ["Behavioral", "Values"],
      },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 79,
    averagePackage: 28,
  },
  {
    id: "stripe",
    name: "Stripe",
    logo: "💳",
    industry: "Financial Technology",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Payment processing and financial services",
    website: "stripe.com",
    founded: 2010,
    activeRoles: ["Software Engineer", "Backend Engineer", "Full-stack Engineer", "ML Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 7.4,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "SDE 1", min: 22, max: 28, location: "Bangalore" },
      { level: "SDE 2", min: 35, max: 48, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding problems",
        difficulty: "hard",
        topics: ["DSA", "Optimization"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Payment system design",
        difficulty: "hard",
        topics: ["System Architecture", "Distributed Systems"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Culture and values",
        difficulty: "medium",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 81,
    averagePackage: 30,
  },
  {
    id: "slack",
    name: "Slack",
    logo: "💬",
    industry: "Software as a Service",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Business communication platform",
    website: "slack.com",
    founded: 2013,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Product Manager"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round",
    minCGPA: 7.2,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "SDE 1", min: 21, max: 27, location: "Bangalore" },
      { level: "SDE 2", min: 33, max: 44, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding assessment",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "Coding and design",
        difficulty: "hard",
        topics: ["System Design", "Architecture"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Problem solving",
        difficulty: "hard",
        topics: ["Algorithms", "Optimization"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Final round", difficulty: "medium", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 77,
    averagePackage: 27,
  },
  {
    id: "notion",
    name: "Notion",
    logo: "📝",
    industry: "Productivity Software",
    size: "Medium",
    headquarters: "San Francisco, USA",
    description: "All-in-one workspace for productivity",
    website: "notion.so",
    founded: 2016,
    activeRoles: ["Software Engineer", "Backend Engineer", "Full-stack Engineer", "Intern"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech", "B.Sc"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "SDE 1", min: 20, max: 26, location: "Bangalore" },
      { level: "SDE 2", min: 31, max: 42, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding round",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round",
        description: "System design and coding",
        difficulty: "hard",
        topics: ["System Architecture", "Advanced DSA"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Culture and fit",
        difficulty: "easy",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 75,
    averagePackage: 26,
  },
  {
    id: "databricks",
    name: "Databricks",
    logo: "🔗",
    industry: "Data & AI",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Data and AI platform company",
    website: "databricks.com",
    founded: 2013,
    activeRoles: ["Software Engineer", "Data Engineer", "ML Engineer", "Solutions Architect"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Sep-Nov, Mar-May",
    minCGPA: 7.2,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 21, max: 27, location: "Bangalore" },
      { level: "Senior Engineer", min: 36, max: 50, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding and DSA",
        difficulty: "hard",
        topics: ["Algorithms", "Data Structures"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Distributed Systems", "Architecture"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Problem solving",
        difficulty: "hard",
        topics: ["Advanced DSA", "Optimization"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Leadership", difficulty: "medium", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 76,
    averagePackage: 28,
  },
  {
    id: "uber-eats",
    name: "Uber Eats",
    logo: "🍕",
    industry: "Food Delivery",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Food delivery service by Uber",
    website: "ubereats.com",
    founded: 2014,
    activeRoles: ["Backend Engineer", "Android Engineer", "Data Engineer", "ML Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Continuous",
    minCGPA: 6.8,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer 1", min: 19, max: 25, location: "Bangalore" },
      { level: "Software Engineer 2", min: 29, max: 38, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding assessment",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "DSA and coding",
        difficulty: "hard",
        topics: ["Algorithms", "Optimization"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "System design",
        difficulty: "hard",
        topics: ["System Architecture", "Scalability"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR interview", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Nov 2024",
    placementRate: 78,
    averagePackage: 24,
  },
  {
    id: "discord",
    name: "Discord",
    logo: "🎮",
    industry: "Communication Software",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Voice, video, and text communication platform",
    website: "discord.com",
    founded: 2015,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Intern"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 7.1,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 21, max: 27, location: "Bangalore" },
      { level: "Senior Engineer", min: 35, max: 48, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Coding Round",
        description: "LeetCode style problems",
        difficulty: "hard",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Design at scale",
        difficulty: "hard",
        topics: ["Distributed Systems", "Architecture"],
      },
      {
        roundNumber: 3,
        name: "Behavioral",
        description: "Culture and values",
        difficulty: "medium",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 73,
    averagePackage: 26,
  },
  {
    id: "figma",
    name: "Figma",
    logo: "🎨",
    industry: "Design Software",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Collaborative design and prototyping platform",
    website: "figma.com",
    founded: 2012,
    activeRoles: ["Software Engineer", "Full-stack Engineer", "ML Engineer", "Intern"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Aug-Oct, Feb-Apr",
    minCGPA: 7.2,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 22, max: 28, location: "Bangalore" },
      { level: "Senior Engineer", min: 37, max: 52, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding and problem solving",
        difficulty: "medium",
        topics: ["DSA"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["System Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA", "Algorithms"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Final round", difficulty: "medium", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 72,
    averagePackage: 27,
  },
  {
    id: "dropbox",
    name: "Dropbox",
    logo: "📦",
    industry: "Cloud Storage",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "File hosting and cloud storage service",
    website: "dropbox.com",
    founded: 2008,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Data Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Sep-Oct",
    minCGPA: 7.1,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 20, max: 26, location: "Bangalore" },
      { level: "Senior Engineer", min: 34, max: 48, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding assessment",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["System Architecture"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Coding and optimization",
        difficulty: "hard",
        topics: ["Algorithms", "Optimization"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR interview", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 74,
    averagePackage: 25,
  },
  {
    id: "atlassian",
    name: "Atlassian",
    logo: "⚙️",
    industry: "Software Development Tools",
    size: "Large",
    headquarters: "Sydney, Australia",
    description: "Software development and collaboration tools",
    website: "atlassian.com",
    founded: 2002,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Frontend Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Sep-Nov, Mar-May",
    minCGPA: 6.9,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 19, max: 25, location: "Bangalore" },
      { level: "Senior Engineer", min: 32, max: 45, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding problems",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Culture fit", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 75,
    averagePackage: 24,
  },
  {
    id: "shopify",
    name: "Shopify",
    logo: "🛍️",
    industry: "E-commerce Platform",
    size: "Large",
    headquarters: "Ottawa, Canada",
    description: "E-commerce platform for online stores",
    website: "shopify.com",
    founded: 2006,
    activeRoles: ["Software Engineer", "Backend Engineer", "Full-stack Engineer", "ML Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Aug-Oct",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 20, max: 26, location: "Bangalore" },
      { level: "Senior Engineer", min: 33, max: 46, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding round",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Coding and design",
        difficulty: "hard",
        topics: ["Advanced DSA", "Design Patterns"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Final round", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 76,
    averagePackage: 25,
  },
  {
    id: "plaid",
    name: "Plaid",
    logo: "🔗",
    industry: "Financial Technology",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "API for financial services integration",
    website: "plaid.com",
    founded: 2013,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Data Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 7.1,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 21, max: 27, location: "Bangalore" },
      { level: "Senior Engineer", min: 35, max: 50, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding problems",
        difficulty: "hard",
        topics: ["DSA", "Optimization"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Distributed Systems", "Architecture"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Problem solving",
        difficulty: "hard",
        topics: ["Advanced DSA", "Algorithms"],
      },
      {
        roundNumber: 4,
        name: "Behavioral",
        description: "Leadership and values",
        difficulty: "medium",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 71,
    averagePackage: 27,
  },
  {
    id: "square",
    name: "Square",
    logo: "⬜",
    industry: "Financial Services",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Payments and point-of-sale systems",
    website: "square.com",
    founded: 2009,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Full-stack Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 6.9,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 20, max: 26, location: "Bangalore" },
      { level: "Senior Engineer", min: 33, max: 46, location: "Bangalore" },
    ],
    interviewProcess: [
      { roundNumber: 1, name: "Phone Screen", description: "Coding assessment", difficulty: "medium", topics: ["DSA"] },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA", "Optimization"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR interview", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 73,
    averagePackage: 24,
  },
  {
    id: "twilio",
    name: "Twilio",
    logo: "☎️",
    industry: "Cloud Communications",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Cloud communications platform",
    website: "twilio.com",
    founded: 2008,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Data Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Aug-Oct",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 20, max: 26, location: "Bangalore" },
      { level: "Senior Engineer", min: 34, max: 48, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Coding Round",
        description: "LeetCode style problems",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Design at scale",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round",
        description: "Advanced problems",
        difficulty: "hard",
        topics: ["Advanced DSA", "Algorithms"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Final round", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 74,
    averagePackage: 25,
  },
  {
    id: "segment",
    name: "Segment",
    logo: "📊",
    industry: "Customer Data Platform",
    size: "Medium",
    headquarters: "San Francisco, USA",
    description: "Customer data infrastructure platform",
    website: "segment.com",
    founded: 2011,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Data Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round",
    minCGPA: 6.9,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 19, max: 25, location: "Bangalore" },
      { level: "Senior Engineer", min: 31, max: 44, location: "Bangalore" },
    ],
    interviewProcess: [
      { roundNumber: 1, name: "Phone Screen", description: "Coding assessment", difficulty: "medium", topics: ["DSA"] },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Problem solving",
        difficulty: "hard",
        topics: ["Advanced DSA"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Culture fit", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 70,
    averagePackage: 23,
  },
  {
    id: "brex",
    name: "Brex",
    logo: "💳",
    industry: "Financial Technology",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Financial services for businesses",
    website: "brex.com",
    founded: 2012,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Full-stack Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 7.2,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 22, max: 28, location: "Bangalore" },
      { level: "Senior Engineer", min: 36, max: 52, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding problems",
        difficulty: "hard",
        topics: ["DSA", "Optimization"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Distributed Systems", "Architecture"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA", "Algorithms"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Final round", difficulty: "medium", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 69,
    averagePackage: 29,
  },
  {
    id: "ramp",
    name: "Ramp",
    logo: "📈",
    industry: "Financial Technology",
    size: "Large",
    headquarters: "New York, USA",
    description: "Corporate spend management platform",
    website: "ramp.com",
    founded: 2019,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Full-stack Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 7.1,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 21, max: 27, location: "Bangalore" },
      { level: "Senior Engineer", min: 34, max: 48, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding and problem solving",
        difficulty: "medium",
        topics: ["DSA"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Leadership", difficulty: "medium", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 68,
    averagePackage: 26,
  },
  {
    id: "carta",
    name: "Carta",
    logo: "📋",
    industry: "Financial Services",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "Cap table and equity management platform",
    website: "carta.com",
    founded: 2012,
    activeRoles: ["Software Engineer", "Backend Engineer", "ML Engineer", "Data Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Sep-Oct",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 20, max: 26, location: "Bangalore" },
      { level: "Senior Engineer", min: 32, max: 45, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding problems",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Problem solving",
        difficulty: "hard",
        topics: ["Advanced DSA"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR interview", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 71,
    averagePackage: 24,
  },
  {
    id: "rippling",
    name: "Rippling",
    logo: "🌐",
    industry: "HR & IT Management",
    size: "Large",
    headquarters: "San Francisco, USA",
    description: "HR and IT management platform",
    website: "rippling.com",
    founded: 2016,
    activeRoles: ["Software Engineer", "Backend Engineer", "Full-stack Engineer", "ML Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Aug-Oct",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 20, max: 26, location: "Bangalore" },
      { level: "Senior Engineer", min: 33, max: 47, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Phone Screen",
        description: "Coding assessment",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Coding and optimization",
        difficulty: "hard",
        topics: ["Advanced DSA"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Final round", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 72,
    averagePackage: 25,
  },
  {
    id: "canva",
    name: "Canva",
    logo: "🎭",
    industry: "Design Software",
    size: "Large",
    headquarters: "Sydney, Australia",
    description: "Online design and publishing platform",
    website: "canva.com",
    founded: 2013,
    activeRoles: ["Software Engineer", "Full-stack Engineer", "ML Engineer", "Data Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Aug-Oct",
    minCGPA: 7.1,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 21, max: 27, location: "Bangalore" },
      { level: "Senior Engineer", min: 35, max: 50, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding problems",
        difficulty: "medium",
        topics: ["DSA"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA", "Algorithms"],
      },
      {
        roundNumber: 4,
        name: "Behavioral",
        description: "Culture and values",
        difficulty: "easy",
        topics: ["Behavioral"],
      },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 73,
    averagePackage: 26,
  },
  {
    id: "razorpay",
    name: "Razorpay",
    logo: "💳",
    industry: "Financial Technology",
    size: "Large",
    headquarters: "Bangalore, India",
    description: "Payment gateway and financial services",
    website: "razorpay.com",
    founded: 2014,
    activeRoles: ["Backend Engineer", "Frontend Engineer", "Full-stack Engineer", "ML Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Aug-Oct, Feb-Apr",
    minCGPA: 6.5,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer 1", min: 12, max: 16, location: "Bangalore" },
      { level: "Software Engineer 2", min: 20, max: 28, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Round",
        description: "Coding problems",
        difficulty: "hard",
        topics: ["DSA", "Optimization"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design and coding",
        difficulty: "hard",
        topics: ["System Architecture", "Advanced DSA"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Problem solving",
        difficulty: "hard",
        topics: ["Algorithms", "Optimization"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR and fit", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 84,
    averagePackage: 18,
  },
  {
    id: "freshworks",
    name: "Freshworks",
    logo: "🌿",
    industry: "Customer Engagement",
    size: "Large",
    headquarters: "Chennai, India",
    description: "Customer relationship management software",
    website: "freshworks.com",
    founded: 2010,
    activeRoles: ["Software Engineer", "Full-stack Engineer", "ML Engineer", "Data Engineer"],
    hiringTrend: "stable",
    seasonalPattern: "Peak: Sep-Nov, Feb-Apr",
    minCGPA: 6.6,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 11, max: 15, location: "Bangalore" },
      { level: "Senior Engineer", min: 18, max: 25, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding and problem solving",
        difficulty: "medium",
        topics: ["DSA"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR interview", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 80,
    averagePackage: 15,
  },
  {
    id: "zoho",
    name: "Zoho",
    logo: "⚡",
    industry: "Software as a Service",
    size: "Large",
    headquarters: "Chennai, India",
    description: "Cloud-based business software suite",
    website: "zoho.com",
    founded: 1996,
    activeRoles: ["Software Developer", "Full-stack Developer", "ML Engineer", "Data Scientist"],
    hiringTrend: "stable",
    seasonalPattern: "Continuous, peak Oct-Dec",
    minCGPA: 6.4,
    degreeRequirements: ["B.Tech", "M.Tech", "B.Sc"],
    branchesAccepted: ["CSE", "IT", "All Branches"],
    salaryRanges: [
      { level: "Developer", min: 9, max: 13, location: "Bangalore" },
      { level: "Senior Developer", min: 16, max: 23, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Test",
        description: "Aptitude and coding",
        difficulty: "easy",
        topics: ["General Aptitude", "Programming"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "Coding and DSA",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "System design",
        difficulty: "medium",
        topics: ["Architecture", "Design Patterns"],
      },
      { roundNumber: 4, name: "HR Round", description: "HR interview", difficulty: "easy", topics: ["HR"] },
    ],
    lastHiringCycle: "Dec 2024",
    placementRate: 87,
    averagePackage: 13,
  },
  {
    id: "mindtree",
    name: "Mindtree",
    logo: "🌳",
    industry: "IT Services",
    size: "Large",
    headquarters: "Bangalore, India",
    description: "Global IT services and digital transformation",
    website: "mindtree.com",
    founded: 1999,
    activeRoles: ["Associate", "Software Engineer", "Senior Software Engineer", "Manager"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Nov-Jan",
    minCGPA: 6.0,
    degreeRequirements: ["B.Tech", "B.Sc", "B.C.A"],
    branchesAccepted: ["CSE", "IT", "ECE"],
    salaryRanges: [
      { level: "Associate", min: 4.5, max: 5.5, location: "Bangalore" },
      { level: "SDE", min: 7.0, max: 10.0, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Written Test",
        description: "Aptitude and technical",
        difficulty: "easy",
        topics: ["General Aptitude", "Programming"],
      },
      {
        roundNumber: 2,
        name: "Technical Round",
        description: "Technical skills assessment",
        difficulty: "medium",
        topics: ["DSA", "Programming"],
      },
      {
        roundNumber: 3,
        name: "HR Round",
        description: "HR interview",
        difficulty: "easy",
        topics: ["HR", "Behavioral"],
      },
    ],
    lastHiringCycle: "Jan 2025",
    placementRate: 88,
    averagePackage: 6.5,
  },
  {
    id: "synopsys",
    name: "Synopsys",
    logo: "🔧",
    industry: "Semiconductor & Software",
    size: "Large",
    headquarters: "Mountain View, USA",
    description: "Electronic design automation and semiconductor software",
    website: "synopsys.com",
    founded: 1986,
    activeRoles: ["Software Engineer", "Hardware Engineer", "ML Engineer", "Intern"],
    hiringTrend: "increasing",
    seasonalPattern: "Peak: Aug-Oct, Feb-Apr",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "ECE"],
    salaryRanges: [
      { level: "Software Engineer", min: 20, max: 26, location: "Bangalore" },
      { level: "Senior Engineer", min: 34, max: 48, location: "Bangalore" },
    ],
    interviewProcess: [
      { roundNumber: 1, name: "Phone Screen", description: "Coding assessment", difficulty: "medium", topics: ["DSA"] },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA", "Algorithms"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Final round", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 77,
    averagePackage: 25,
  },
  {
    id: "cadence",
    name: "Cadence Design Systems",
    logo: "🎯",
    industry: "Semiconductor Software",
    size: "Large",
    headquarters: "San Jose, USA",
    description: "Electronic design automation software",
    website: "cadence.com",
    founded: 1988,
    activeRoles: ["Software Engineer", "Design Engineer", "ML Engineer", "Intern"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Aug-Oct",
    minCGPA: 6.9,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "ECE"],
    salaryRanges: [
      { level: "Software Engineer", min: 19, max: 25, location: "Bangalore" },
      { level: "Senior Engineer", min: 32, max: 45, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Coding Round",
        description: "DSA problems",
        difficulty: "medium",
        topics: ["Data Structures", "Algorithms"],
      },
      {
        roundNumber: 2,
        name: "System Design",
        description: "Design at scale",
        difficulty: "hard",
        topics: ["Architecture", "Scalability"],
      },
      {
        roundNumber: 3,
        name: "Technical Round",
        description: "Advanced problems",
        difficulty: "hard",
        topics: ["Advanced DSA"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR interview", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 75,
    averagePackage: 24,
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    logo: "🎮",
    industry: "Semiconductor & AI",
    size: "Large",
    headquarters: "Santa Clara, USA",
    description: "GPU and AI semiconductor company",
    website: "nvidia.com",
    founded: 1993,
    activeRoles: ["Software Engineer", "Hardware Engineer", "ML Engineer", "Systems Engineer"],
    hiringTrend: "increasing",
    seasonalPattern: "Year-round, peak Sep-Nov",
    minCGPA: 7.2,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "ECE", "IT"],
    salaryRanges: [
      { level: "Software Engineer", min: 23, max: 29, location: "Bangalore" },
      { level: "Senior Engineer", min: 38, max: 54, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding and DSA",
        difficulty: "hard",
        topics: ["Algorithms", "Optimization"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Distributed Systems", "GPU Computing"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced problems",
        difficulty: "hard",
        topics: ["Advanced DSA", "Performance Optimization"],
      },
      {
        roundNumber: 4,
        name: "Behavioral",
        description: "Final round",
        difficulty: "medium",
        topics: ["Behavioral", "Leadership"],
      },
    ],
    lastHiringCycle: "Oct 2024",
    placementRate: 80,
    averagePackage: 28,
  },
  {
    id: "intel",
    name: "Intel",
    logo: "💻",
    industry: "Semiconductor",
    size: "Large",
    headquarters: "Santa Clara, USA",
    description: "Semiconductor and computing company",
    website: "intel.com",
    founded: 1968,
    activeRoles: ["Software Engineer", "Hardware Engineer", "ML Engineer", "Intern"],
    hiringTrend: "stable",
    seasonalPattern: "Year-round, peak Aug-Oct",
    minCGPA: 6.8,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "ECE"],
    salaryRanges: [
      { level: "Software Engineer", min: 19, max: 25, location: "Bangalore" },
      { level: "Senior Engineer", min: 31, max: 44, location: "Bangalore" },
    ],
    interviewProcess: [
      { roundNumber: 1, name: "Phone Screen", description: "Coding assessment", difficulty: "medium", topics: ["DSA"] },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA"],
      },
      { roundNumber: 4, name: "Behavioral", description: "HR interview", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 76,
    averagePackage: 23,
  },
  {
    id: "qualcomm",
    name: "Qualcomm",
    logo: "📱",
    industry: "Semiconductor & Wireless",
    size: "Large",
    headquarters: "San Diego, USA",
    description: "Semiconductor and telecommunications equipment company",
    website: "qualcomm.com",
    founded: 1985,
    activeRoles: ["Software Engineer", "Hardware Engineer", "ML Engineer", "Intern"],
    hiringTrend: "stable",
    seasonalPattern: "Peak: Aug-Oct, Feb-Apr",
    minCGPA: 7.0,
    degreeRequirements: ["B.Tech", "M.Tech"],
    branchesAccepted: ["CSE", "ECE"],
    salaryRanges: [
      { level: "Software Engineer", min: 20, max: 26, location: "Bangalore" },
      { level: "Senior Engineer", min: 33, max: 47, location: "Bangalore" },
    ],
    interviewProcess: [
      {
        roundNumber: 1,
        name: "Online Assessment",
        description: "Coding problems",
        difficulty: "medium",
        topics: ["DSA", "Problem Solving"],
      },
      {
        roundNumber: 2,
        name: "Technical Round 1",
        description: "System design",
        difficulty: "hard",
        topics: ["Architecture", "Wireless Systems"],
      },
      {
        roundNumber: 3,
        name: "Technical Round 2",
        description: "Advanced coding",
        difficulty: "hard",
        topics: ["Advanced DSA", "Optimization"],
      },
      { roundNumber: 4, name: "Behavioral", description: "Final round", difficulty: "easy", topics: ["Behavioral"] },
    ],
    lastHiringCycle: "Sep 2024",
    placementRate: 77,
    averagePackage: 25,
  },
]
